version: '3.8'

services:
  node-app:
    container_name: node-app
    restart: always
    build:
      context: ./
    environment:
      - VIRTUAL_HOST=tvmirror.io
      - HTTPS_METHOD=noredirect
      - LETSENCRYPT_HOST=tvmirror.io
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_EMAIL=admin@tvmirror.io
    networks:
      - wsserver-network

  nginx-proxy:
    container_name: wsserver-nginx-proxy
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - HTTPS_METHOD=noredirect
    networks:
      - wsserver-network
    depends_on:
      - node-app

  acme-companion:
    container_name: wsserver-acme-companion
    image: nginxproxy/acme-companion
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - wsserver-network
    depends_on:
      - nginx-proxy

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  wsserver-network:
    driver: bridge
